Dataframe docs update
writer/writer-framework pull request #693
Opened 2024-12-14 15:58 UTC by AccordionGuy

Here’s the first of many rapid updates to the documentation for DataFrame. This one covers displaying DataFrames and the methods for the `EditableDataframe` class.

2024-12-15 17:55 UTC, madeindjs reviewed
Well done :muscle: I spotted some small mistakes, but it should be good.

2024-12-15 17:55 UTC, madeindjs commented on docs/framework/dataframe.mdx
> +			```sh pandas
Shouldn't it be Python code?
```suggestion
			```python pandas
```

2024-12-15 17:55 UTC, madeindjs commented on docs/framework/dataframe.mdx
> +			```sh Polars
```suggestion
			```python Polars
```

2024-12-15 17:55 UTC, madeindjs commented on docs/framework/dataframe.mdx
> +			```sh pandas
```suggestion
			```python pandas
```

2024-12-15 17:55 UTC, madeindjs commented on docs/framework/dataframe.mdx
> +			```sh Polars
```suggestion
			```python Polars
```

2024-12-15 17:55 UTC, madeindjs commented on docs/framework/dataframe.mdx
> +			```sh List of dictionaries
```suggestion
			```python List of dictionaries
```

2024-12-15 17:55 UTC, madeindjs commented on docs/framework/dataframe.mdx
> +state["mydf"].record_remove({"record_index": 0})
The previous line says to remove row index 2

https://github.com/writer/writer-framework/blob/014cc21c5d444783108bba6d03a0635536641a12/docs/framework/dataframe.mdx?plain=1#L202

So it should be
```suggestion
state["mydf"].record_remove({"record_index": 2})
```

2024-12-16 08:34 UTC, ramedina86 commented on docs/framework/dataframe.mdx
> +<Note>Note that the "f" in `EditableDataframe` is _not_ capitalized — it’s `EditableDataframe`, not `EditableDataFrame`!</Note>
@samjulien @ajot @AccordionGuy in general, if you find yourself writing something like this, please provide feedback and we'll likely fix it on our end 😀

2024-12-16 09:16 UTC, ramedina86 commented on docs/framework/dataframe.mdx
> +<Note>Note that the "f" in `EditableDataframe` is _not_ capitalized — it’s `EditableDataframe`, not `EditableDataFrame`!</Note>
So you'll change from `EditableDataframe` to `EditableDataFrame`?

2024-12-16 09:22 UTC, FabienArcellier commented on docs/framework/dataframe.mdx
> +<Note>Note that the "f" in `EditableDataframe` is _not_ capitalized — it’s `EditableDataframe`, not `EditableDataFrame`!</Note>
Sorry, bad reading for my comment on github. Ok for me to go to `EditableDataFrame`.

2024-12-16 15:52 UTC, AccordionGuy commented on docs/framework/dataframe.mdx
> +<Note>Note that the "f" in `EditableDataframe` is _not_ capitalized — it’s `EditableDataframe`, not `EditableDataFrame`!</Note>
@ramedina86 @FabienArcellier I've made the updates as requested and will let you folks know if I find potential issues like the capitalization of `EditableDataframe` —  I figured that there might be a good reason for the original capitalization, but I’ll ask next time!

2024-12-16 15:57 UTC, ramedina86 commented on docs/framework/dataframe.mdx
> +<Note>Note that the "f" in `EditableDataframe` is _not_ capitalized — it’s `EditableDataframe`, not `EditableDataFrame`!</Note>
Thanks @AccordionGuy 🙏🏻

2024-12-19 00:42 UTC, samjulien requested changes
Few corrections needed and a little intro and conclusion cleanup

2024-12-19 00:42 UTC, samjulien commented on docs/framework/dataframe.mdx
> +**Writer Framework has two objects with the name _DataFrame_:**
Can we add an intro sentence here to help people understand what they're trying to accomplish with dataframes?

2024-12-19 00:42 UTC, samjulien commented on docs/framework/dataframe.mdx
> +		Add a DataFrame UI component to the user interface, then set its **Data** property to `@{`_dataframe_key_`}`, where _dataframe_key_ is the `state` variable key whose value refers to the `DataFrame`
The underscores at the front and end of `_dataframe_key_` add italics and break the code formatting, I'd remove them.

2024-12-19 00:42 UTC, samjulien commented on docs/framework/dataframe.mdx
> +		![DataFrame for static table example with properties panel open](images/dataframe_static_table_1.png)
This image is broken for me, might want to double check the URL against other docs. I think you need to add /framework to the front possibly but check out other examples.

2024-12-19 00:42 UTC, samjulien commented on docs/framework/dataframe.mdx
> +			```sh Polars
☝️ ➕

2024-12-19 00:42 UTC, samjulien commented on docs/framework/dataframe.mdx
> +			```sh List of dictionaries
☝️ ➕

2024-12-19 00:42 UTC, samjulien commented on docs/framework/dataframe.mdx
> +		![DataFrame for dynamic table example with properties panel open](images/dataframe_dynamic_table_1.png)
Ditto on image URL being broken

2024-12-19 00:42 UTC, samjulien commented on docs/framework/dataframe.mdx
> +state["mydf"].record_remove({"record_index": 2})
Seems like this is missing a conclusion or something to wrap this up and tell the user where to go next

2024-12-19 00:42 UTC, samjulien commented on docs/framework/dataframe.mdx
> +## Displaying a static DataFrame
Can we please briefly discuss the options in the DataFrame component (e.g. sorting, downloading, searching) and link to the component documentation.

2024-12-19 16:11 UTC, samjulien commented
Updates look great @AccordionGuy! @ramedina86 @FabienArcellier this is ready for you all to review and merge! Once that's done we'll need to update the main mintlify.json in the docs repo -- happy to do it unless you already have that as part of your process, I know Fabien was looking at automating this.

2025-01-02 18:35 UTC, samjulien commented
@FabienArcellier just bumping this for visibility once you're back from the holidays. Would love to finally get Dataframe documented! Thank you!

2025-01-03 17:19 UTC, FabienArcellier approved these changes

2025-01-03 17:25 UTC, FabienArcellier commented
I review and fix conflicts. It looks ok. I would advocate to explain on how to use `record_add`, `record_update` and `record_remove` in event handler (maybe screenshot or small video). This method are design to be compliant with event handler `payload`.

```python
# Subscribe this event handler to the `wf-dataframe-add` event
#
# more on : https://dev.writer.com/framework/dataframe
def on_record_add(state, payload):
	payload['record']['sales'] = 0 # default value inside the dataframe
	state['mydf'].record_add(payload) # should contain an EditableDataFrame instance
```

2025-01-03 17:28 UTC, FabienArcellier commented
@samjulien I haven't work on the topic of automatic table of content generation. It would focus on generated contents (components and later on workflow blocks), not on editorialized pages as Dataframe or ai-modules.

2025-01-03 21:03 UTC, samjulien commented
Thanks @FabienArcellier! Let's go ahead with this -- I've added a Jira ticket to the Docs & DX board for making your suggested updates in the next iteration of this doc. Whenever it's released I'll manually add to the main Mintlify nav in the docs repo.

2025-01-03 21:21 UTC, merged